# Name of this GitHub Actions workflow.
name: Run SAST Scan

on:
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  
jobs:
  SemgrepScan:
    # User-definable name of this GitHub Actions job:

    # If you are self-hosting, change the following `runs-on` value: 
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: returntocorp/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout.
      - name: Checkout Repo
      - uses: actions/checkout@v3

      - name: Execute Semgrep SAST Scan
      # Run the "semgrep ci" command on the command line of the docker image.
      - run: semgrep ci --sarif > /__w/_temp/findings.sarif || true
        env:
           # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable. 
           SEMGREP_RULES: p/default # more at semgrep.dev/explore

      - name: Upload SARIF Artifact to Repo     
      - uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: /home/runner/work/_temp/findings.sarif
          # Optional category for the results
          #  Used to differentiate multiple results for one commit
          category: Semgrep
